# Generated by Django 4.2.2 on 2023-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PullRequest",
        ),
    ]
